blog/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings  
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from post.views import *
from home.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_views,name="index"),
    path('editorial',editorial_views,name="editorial"),
    path('guideline',guideline_views,name="guideline"),
    path('abstracted',abstracted_views,name="abstracted"),
    path('submission',submission_views,name="submission"),
    path('category',category_views,name="category"),
    path('category/<str:name>/',categoryid_views,name="categoryid"),
    path('categorydetails',categorydetails_views,name="categorydetails"), 
    path('categorydetails/<int:id>/',categorydetailid_views,name="categorydetailid"), 
    
    path('dashboard/', include('dashboard.urls')),

 
  
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from .views import *
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView, LogoutView

app_name = "dashboard"
urlpatterns = [

    path("password/", password_views,name='password'),
    
    path('users',users_views,name="users"), 
    path('updateuser/<int:id>',update_user,name="updateuser"),
    path('deleteuser/<int:id>',delete_user,name="deleteuser"), 
    
    
    
    path('pages',pages_views,name="pages"),
    path('page1',page1_views,name="page1"),   
    path('page2',page2_views,name="page2"),  
    path('page3',page3_views,name="page3"),  
    path('page4',page4_views,name="page4"), 
    
    path('edit_page1/<int:id>',edit_page1_views,name="edit_page1"),
    path('edit_page2/<int:id>',edit_page2_views,name="edit_page2"),    
    path('edit_page3/<int:id>',edit_page3_views,name="edit_page3"),    
    path('edit_page4/<int:id>',edit_page4_views,name="edit_page4"), 
     
    path('posts',posts_views,name="posts"),  
    path('adduser',add_user_views,name="adduser"),  
    path('addpost',add_post_views,name="addpost"),
    path('updatepost/<int:id>',update_post,name="updatepost"),
    path('deletepost/<int:id>',delete_post,name="deletepost"), 
 
 
 
    path('authors',authors_views,name="authors"), 
    path('addauthors',add_authors_views,name="addauthors"),  
    path('editauthors/<int:id>',edit_authors_views,name="editauthors"),
    path('deleteauthors/<int:id>',delete_authors_views,name="deleteauthors"),


    path('addtags',add_tags_views,name="addtags"),  
    path('edittags/<int:id>',edit_tags_views,name="edittags"),
    path('deletetags/<int:id>',delete_tags_views,name="deletetags"),

   
     
    path('images/<int:id>',images_views,name="images"),  
    path('submissions',submissions_views,name="submissions"),

    
    path('login/', LoginView.as_view(), name="custom_login"),
    path("logout/", LogoutView.as_view(), name="logout"),


    
]   

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)
    

dashboard/models.py
from django.db import models

from post.models import *


# Create your models here.

dashboard/forms.py
from django import forms
from django.forms import ModelForm
from matplotlib import widgets

from post.models import Article_Author, Image, Page1, Page2, Page3, Page4, Tag, User,Article  
from django.contrib.auth.forms import UserCreationForm ,UserChangeForm ,PasswordChangeForm


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model=User  
        fields = ('first_name','last_name','username', 'email') 
        
        labels = {
            'first_name':'First Name',
            'last_name':'Last Name',
            'username':'Username',
            'email':'Email',
        }
        
        widgets = {
            'first_name':forms.TextInput(attrs={'class':'form-control'}),
            'last_name':forms.TextInput(attrs={'class':'form-control'}),
            'username':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'}),

        }
  
     
     
class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model=User 
        fields = ('first_name','last_name','username', 'email')
        
        
        labels = {
            'first_name':'First Name',
            'last_name':'Last Name',
            'username':'Username',
            'email':'Email',
        }
        
        widgets = {
            'first_name':forms.TextInput(attrs={'class':'form-control'}),
            'last_name':forms.TextInput(attrs={'class':'form-control'}),
            'username':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'}),

        }
         
         
         
         
         

        
      
      
      
class PostForm(ModelForm):
    class Meta:
        model = Article
        fields = ('category','article_author','title','text','tag','fileurl')

        labels = {
            'category':'Category',
            'title':'Title',
            'text':'Text',
            'tag':'Tags',
            'fileurl':'FileUrl'
        }
        
        widgets = {
            'category':forms.TextInput(attrs={'class':'form-control'}),
            'title':forms.TextInput(attrs={'class':'form-control'}),
            'text':forms.Textarea(attrs={'class':'form-control'}),
            'fileurl':forms.FileInput(attrs={'class':'form-control'}),

        }
        
        


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['RightBarImage','LeftBarImage']
        
        labels = {
            'RightBarImage':'RightBarImage',
            'LeftBarImage':'LeftBarImage',
        }
        
        widgets = {
            'RightBarImage':forms.FileInput(attrs={'class':'form-control'}),
            'LeftBarImage':forms.FileInput(attrs={'class':'form-control'}),
        }
        
        
 
    
class Page1Form(forms.ModelForm):
    class Meta:
        model = Page1
        fields = ('pagename','title','text')
        
        labels = {
            'pagename':'Page name',
            'title':'Title',
            'text':'Text',
        }
        
        widgets = {
            'pagename':forms.TextInput(attrs={'class':'form-control'}),
            'title':forms.TextInput(attrs={'class':'form-control'}),
            'text':forms.Textarea(attrs={'class':'form-control'}),
        }
        
        
class Page2Form(forms.ModelForm):
    class Meta:
        model = Page2
        fields = ('pagename','title','text')
        
        labels = {
            'pagename':'Page name',
            'title':'Title',
            'text':'Text',
        }
        
        widgets = {
            'pagename':forms.TextInput(attrs={'class':'form-control'}),
            'title':forms.TextInput(attrs={'class':'form-control'}),
            'text':forms.Textarea(attrs={'class':'form-control'}),
        }
        
class Page3Form(forms.ModelForm):
    class Meta:
        model = Page3
        fields = ('pagename','title','text')
        
        labels = {
            'pagename':'Page name',
            'title':'Title',
            'text':'Text',
        }
        
        widgets = {
            'pagename':forms.TextInput(attrs={'class':'form-control'}),
            'title':forms.TextInput(attrs={'class':'form-control'}),
            'text':forms.Textarea(attrs={'class':'form-control'}),
        }
        
class Page4Form(forms.ModelForm):
    class Meta:
        model = Page4
        fields = ('pagename','title','text')
        
        labels = {
            'pagename':'Page name',
            'title':'Title',
            'text':'Text',
        }
        
        widgets = {
            'pagename':forms.TextInput(attrs={'class':'form-control'}),
            'title':forms.TextInput(attrs={'class':'form-control'}),
            'text':forms.Textarea(attrs={'class':'form-control'}),
        }
        
        
        
class AuthorForms(forms.ModelForm):
    class Meta:
        model = Article_Author
        
        fields = ('name',)
        
        labels = {
            'name':'Name',
        }
        
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'}),
        }

        
    
    
    
class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        
        fields = ('text',)
        
        labels = {
            'text':'Text',
        }
        
        widgets = {
            'text':forms.TextInput(attrs={'class':'form-control'}),
        }
        

                

dashboard/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from .forms import *
from post.models import *


def password_views(request):
    return render(request,'registration/password.html')    
    
    
@login_required(login_url='/dashboard/login/')
# Create your views here.
def users_views(request):
    my_user = User.objects.all()

    context = {

        'my_user': my_user,

    }
    return render(request, 'dashboard/users.html', context)


@login_required(login_url='/dashboard/login/')
def add_user_views(request):
    form = CustomUserCreationForm(request.POST or None, request.FILES or None)

    if form.is_valid():

        form.save()

        return redirect("dashboard:users")
    return render(request, "dashboard/adduser.html", {"form": form})


@login_required(login_url='/dashboard/login/')
def update_user(request, id):

    deneme = get_object_or_404(User, id=id)
    form = CustomUserChangeForm(
        request.POST or None, request.FILES or None, instance=deneme)
    if form.is_valid():

        form.save()

        return redirect("dashboard:users")

    return render(request, "dashboard/update_user.html", {"form": form})


def delete_user(request, id):
    user = get_object_or_404(User, id=id)
    user.delete()
    return redirect('dashboard:users')


@login_required(login_url='/dashboard/login/')
def pages_views(request):
    return render(request, 'dashboard/pages.html')


@login_required(login_url='/dashboard/login/')
def page1_views(request):
    my_page = Page1.objects.all()

    context = {

        'my_page': my_page,

    }
    return render(request, 'dashboard/page1.html', context)


def edit_page1_views(request, id):
    instance = Page1.objects.get(id=id)
    form = Page1Form(instance=instance)

    if request.method == 'POST':

        form = Page1Form(request.POST or None,
                         request.FILES or None, instance=instance)
        if form.is_valid():

            form.save()

            return redirect("dashboard:pages")

    context = {
        'form': form,
    }
    return render(request, "dashboard/edit_page1.html", context)


def edit_page2_views(request, id):
    instance = Page2.objects.get(id=id)
    form = Page2Form(instance=instance)

    if request.method == 'POST':

        form = Page2Form(request.POST or None,
                         request.FILES or None, instance=instance)
        if form.is_valid():

            form.save()

            return redirect("dashboard:pages")

    context = {
        'form': form,
    }
    return render(request, "dashboard/edit_page2.html", context)


def edit_page3_views(request, id):
    instance = Page3.objects.get(id=id)
    form = Page3Form(instance=instance)

    if request.method == 'POST':

        form = Page3Form(request.POST or None,
                         request.FILES or None, instance=instance)
        if form.is_valid():

            form.save()

            return redirect("dashboard:pages")

    context = {
        'form': form,
    }
    return render(request, "dashboard/edit_page3.html", context)


def edit_page4_views(request, id):
    instance = Page4.objects.get(id=id)
    form = Page4Form(instance=instance)

    if request.method == 'POST':

        form = Page4Form(request.POST or None,
                         request.FILES or None, instance=instance)
        if form.is_valid():

            form.save()

            return redirect("dashboard:pages")

    context = {
        'form': form,
    }
    return render(request, "dashboard/edit_page4.html", context)


@login_required(login_url='/dashboard/login/')
def page2_views(request):
    my_page = Page2.objects.all()

    context = {

        'my_page': my_page,

    }
    return render(request, 'dashboard/page2.html', context)


@login_required(login_url='/dashboard/login/')
def page3_views(request):
    my_page = Page3.objects.all()

    context = {

        'my_page': my_page,

    }
    return render(request, 'dashboard/page3.html', context)


@login_required(login_url='/dashboard/login/')
def page4_views(request):
    my_page = Page4.objects.all()

    context = {

        'my_page': my_page,

    }
    return render(request, 'dashboard/page4.html', context)


@login_required(login_url='/dashboard/login/')
def submissions_views(request):
    my_sub = Submission.objects.all()

    context = {

        'my_sub': my_sub,

    }

    return render(request, 'dashboard/submissions.html', context)


@login_required(login_url='/dashboard/login/')
def posts_views(request):
    my_post = Article.objects.all()

    context = {

        'my_post': my_post,

    }
    return render(request, 'dashboard/posts.html', context)


@login_required(login_url='/dashboard/login/')
def add_post_views(request):
    form = PostForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        article = form.save()

        article.save()

        return redirect("dashboard:posts")
    return render(request, "dashboard/addpost.html", {"form": form})


@login_required(login_url='/dashboard/login/')
def update_post(request, id):

    article = get_object_or_404(Article, id=id)
    form = PostForm(request.POST or None,
                    request.FILES or None, instance=article)
    if form.is_valid():
        article = form.save()

        article.save()

        return redirect("dashboard:posts")

    return render(request, "dashboard/update_posts.html", {"form": form})


def delete_post(request, id):
    post = get_object_or_404(Article, id=id)
    post.delete()
    return redirect('dashboard:posts')


@login_required(login_url='/dashboard/login/')
def images_views(request, id):
    instance = Image.objects.get(id=id)
    form = ImageForm(request.POST, request.FILES, instance=instance)
    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES, instance=instance)

        if form.is_valid():
            form.save()
            return redirect('dashboard:users')
    else:
        form = ImageForm(request.POST, request.FILES, instance=instance)
    return render(request, 'dashboard/images.html', {'form': form})


@login_required(login_url='/dashboard/login/')
def authors_views(request):
    my_post = Article_Author.objects.all()
    my_tags = Tag.objects.all()

    context = {
        'my_post': my_post,
        'my_tags': my_tags,

    }
    return render(request, "dashboard/authors.html", context)





def add_tags_views(request):
    form = TagForm()

    if request.method == 'POST':

        form = TagForm(request.POST or None,
                         request.FILES or None)
        if form.is_valid():

            form.save()

            return redirect("dashboard:authors")

    context = {
        'form': form,
    }
    return render(request, "dashboard/add_tags.html",context)


def edit_tags_views(request, id):
    instance = Tag.objects.get(id=id)
    form = TagForm(instance=instance)

    if request.method == 'POST':

        form = TagForm(request.POST or None,
                         request.FILES or None, instance=instance)
        if form.is_valid():

            form.save()

            return redirect("dashboard:authors")

    context = {
        'form': form,
    }
    return render(request, "dashboard/edit_tags.html", context)


def delete_tags_views(request, id):
    post = get_object_or_404(Tag, id=id)
    post.delete()
    return redirect('dashboard:authors')


# **************
#  AUTHORS
# **************


def add_authors_views(request):
    form = AuthorForms()

    if request.method == 'POST':

        form = AuthorForms(request.POST or None,
                         request.FILES or None)
        if form.is_valid():

            form.save()

            return redirect("dashboard:authors")

    context = {
        'form': form,
    }
    return render(request, "dashboard/addauthors.html", context)




def edit_authors_views(request, id):
    instance = Article_Author.objects.get(id=id)
    form = AuthorForms(instance=instance)

    if request.method == 'POST':

        form = AuthorForms(request.POST or None,
                         request.FILES or None, instance=instance)
        if form.is_valid():

            form.save()

            return redirect("dashboard:authors")

    context = {
        'form': form,
    }
    return render(request, "dashboard/edit_authors.html", context)





def delete_authors_views(request, id):
    post = get_object_or_404(Article_Author, id=id)
    post.delete()
    return redirect('dashboard:authors')




    
    

post/views.py
from django.shortcuts import render

# Create your views here.

templates/dashboard/add_tags.html
{% extends 'dashboard/dsh_base.html' %}
{% load static %}

{% block title %}
  Add Tags
{% endblock title %}

{% block body %}

<br>
<center>
    <h5 style="color: #009CFF;">Add Tags</h5>
</center>


<form  style="margin: 10px; width:400px;" method=POST>
  {% csrf_token %}
  {{ form.as_p }}
  <button style="color: white;" class="btn btn-info" type="submit">Create</button>
</form>

{% endblock body %}

templates/dashboard/addpost.html
{% extends 'dashboard/dsh_base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block title %}
  Add Post
{% endblock title %}


{% block body %}

<br>
<center>
    <h5 style="color: #009CFF;">Create Post</h5>
</center>


<form style="margin: 10px; width:500px;" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}}
    {{ form.as_p }}

    <button style="color: white;" class="btn btn-info" type="submit">Add</button>
</form>




{% endblock body %}

templates/dashboard/adduser.html
{% extends 'dashboard/dsh_base.html' %}
{% load static %}

{% block title %}
  AddUser
{% endblock title %}


{% block body %}
<br>
<center>
    <h5 style="color: #009CFF;">Create User</h5>
</center>




<form style="margin: 10px; width:400px;" method=POST>
    {% csrf_token %}
    {{ form.as_p }}
    <button style="color: white;" class="btn btn-info" type="submit">Add</button>
</form>



{% endblock body %}

templates/dashboard/edit_authors.html
{% extends 'dashboard/dsh_base.html' %}
{% load static %}

{% block title %}
  Authors | Edit
{% endblock title %}

{% block body %}

<br>
<center>
    <h5 style="color: #009CFF;">Authors Edit</h5>
</center>


<form  style="margin: 10px; width:400px;" method=POST>
  {% csrf_token %}
  {{ form.as_p }}
  <button style="color: white;" class="btn btn-info" type="submit">Update</button>
</form>

{% endblock body %}

templates/dashboard/edit_page2.html
{% extends 'dashboard/dsh_base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block title %}
  Page 2 | Edit
{% endblock title %}

{% block body %}

<br>
<center>
    <h5 style="color: #009CFF;">Edit Page 2</h5>
</center>


<center>
    <a href="{% url 'dashboard:page1' %}">Page 2</a>
</center>

<form  style="margin: 10px; width:400px;" method=POST>
  {% csrf_token %}
  {{form.media}}

  {{ form.as_p }}
  <button style="color: white;" class="btn btn-info" type="submit">Update</button>
</form>

{% endblock body %}

templates/dashboard/edit_page3.html
{% extends 'dashboard/dsh_base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block title %}
  Page 3 | Edit
{% endblock title %}

{% block body %}

<br>
<center>
    <h5 style="color: #009CFF;">Edit Page 3</h5>
</center>


<center>
    <a href="{% url 'dashboard:page1' %}">Page 3</a>
</center>

<form  style="margin: 10px; width:400px;" method=POST>
  {% csrf_token %}
  {{form.media}}

  {{ form.as_p }}
  <button style="color: white;" class="btn btn-info" type="submit">Update</button>
</form>

{% endblock body %}

templates/dashboard/edit_tags.html
{% extends 'dashboard/dsh_base.html' %}
{% load static %}

{% block title %}
  Tags | Edit
{% endblock title %}

{% block body %}

<br>
<center>
    <h5 style="color: #009CFF;">Tags Edit</h5>
</center>


<form  style="margin: 10px; width:400px;" method=POST>
  {% csrf_token %}
  {{ form.as_p }}
  <button style="color: white;" class="btn btn-info" type="submit">Update</button>
</form>

{% endblock body %}

templates/dashboard/page1.html
{% extends 'dashboard/dsh_base.html' %}
{% load static %}

{% block title %}
  Page 1
{% endblock title %}

{% block body %}
<div class="container-fluid pt-4 px-4">
    <div class="bg-light text-center rounded p-4">
        <div class="d-flex align-items-center justify-content-between mb-4">
            <h6 class="mb-0">Page 1</h6>
        </div>
  
        <div class="table-responsive">
            <table class="table text-start align-middle table-bordered table-hover mb-0">
                <thead>
                    <tr class="text-dark">
                      <th scope="col">Pagename</th>
                      <th scope="col">Title</th>
                      <th scope="col">Text</th>
                    </tr>
                </thead>
                {% for p in my_page %}
                <tbody>
                    <tr>
                        <td>{{p.pagename}}</td>
                        <td>{{p.title}}</td>
                        <td>{{p.text | safe}}</td>
                        <td><center><a class="btn btn-sm btn-primary" href="{% url 'dashboard:edit_page1' p.id %}"><i class="fa-solid fa-gear"></i></a></center></td>
                    </tr>
                </tbody>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock body %}

templates/dashboard/page2.html
{% extends 'dashboard/dsh_base.html' %}
{% load static %}

{% block title %}
  Page 2
{% endblock title %}

{% block body %}
<div class="container-fluid pt-4 px-4">
    <div class="bg-light text-center rounded p-4">
        <div class="d-flex align-items-center justify-content-between mb-4">
            <h6 class="mb-0">Page 2</h6>
        </div>
  
        <div class="table-responsive">
            <table class="table text-start align-middle table-bordered table-hover mb-0">
                <thead>
                    <tr class="text-dark">
                      <th scope="col">Pagename</th>
                      <th scope="col">Title</th>
                      <th scope="col">Text</th>
                    </tr>
                </thead>
                {% for p in my_page %}
                <tbody>
                    <tr>
                        <td>{{p.pagename}}</td>
                        <td>{{p.title}}</td>
                        <td>{{p.text | safe}}</td>
                        <td><center><a class="btn btn-sm btn-primary" href="{% url 'dashboard:edit_page2' p.id %}"><i class="fa-solid fa-gear"></i></a></center></td>
                    </tr>
                </tbody>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock body %}

templates/dashboard/pages.html
{% extends 'dashboard/dsh_base.html' %}
{% load static %}

{% block title %}
  Pages
{% endblock title %}

{% block body %}

<div class="container-fluid pt-4 px-4">
  <div class="bg-light text-center rounded p-4">
      <div class="d-flex align-items-center justify-content-between mb-4">
          <h6 class="mb-0">Pages</h6>
      </div>

      <div class="table-responsive">
          <table class="table text-start align-middle table-bordered table-hover mb-0">
              <tbody>
                  <tr>
                      <td><a href="{% url 'dashboard:page1' %}">Page 1</a></td>
                      <td><a href="{% url 'dashboard:page2' %}">Page 2</a></td>
                      <td><a href="{% url 'dashboard:page3' %}">Page 3</a></td>
                      <td><a href="{% url 'dashboard:page4' %}">Page 4</a></td>
                  </tr>
              </tbody>
          </table>
      </div>
  </div>
</div>


{% endblock body %}

templates/dashboard/posts.html
{% extends 'dashboard/dsh_base.html' %}
{% load static %}

{% block title %}
  Posts
{% endblock title %}

{% block body %}
<!-- Recent Sales Start -->

<div class="container-fluid pt-4 px-4">
  <div class="bg-light text-center rounded p-4">
      <div class="d-flex align-items-center justify-content-between mb-4">
          <h6 class="mb-0">Posts</h6>
          <a class="btn btn-sm btn-primary" href="{% url 'dashboard:addpost' %}"><i class="fa-solid fa-plus"></i></a>
      </div>

      <div class="table-responsive">
          <table class="table text-start align-middle table-bordered table-hover mb-0">
              <thead>
                  <tr class="text-dark">
                    <th scope="col">#</th>
                    <th scope="col">Category</th>
                    <th scope="col">Author Name</th>
                    <th scope="col">Title</th>
                    <th scope="col">Text</th>
                    <th scope="col">Tags</th>
                    <th scope="col">Image</th>

                  </tr>
              </thead>
              {% for p in my_post %}
              <tbody>
                  <tr>
                      <th scope="row">{{ forloop.counter }}</th>
                      <td>{{p.category}}</td>
                      <td>{% for author in p.article_author.all %}  {{author}} ,  {% endfor %}</td>
                      <td>{{p.title}}</td>
                      <td>{{p.text | safe}}</td>
                      <td>{% for tag in p.tag.all %}  {{tag.text}} ,  {% endfor %}</td>

                      {% if p.fileurl %}
                      <td><img style="width: 100px; height:110px;" src="{{p.fileurl.url}}"></td>
                      {% else %}
                      <td>Null</td>
                      {% endif %}
                      <td><center><a class="btn btn-sm btn-primary" href="{% url 'dashboard:updatepost' p.id %}"><i class="fa-solid fa-gear"></i></a></center></td>
                      <td><center><a class="btn btn-sm btn-primary" href="{% url 'dashboard:deletepost' p.id %}"><i class="fa-solid fa-trash"></i></a></center></td>
                  </tr>
              </tbody>
              {% endfor %}
          </table>
      </div>
  </div>
</div>

{% endblock body %}

templates/dashboard/submissions.html
{% extends 'dashboard/dsh_base.html' %}
{% load static %}

{% block title %}
  Submissions
{% endblock title %}

{% block body %}

<!-- Recent Sales Start -->
<div class="container-fluid pt-4 px-4">
    <div class="bg-light text-center rounded p-4">
        <div class="d-flex align-items-center justify-content-between mb-4">
            <h6 class="mb-0">Submissions</h6>
        </div>
        <div class="table-responsive">
            <table class="table text-start align-middle table-bordered table-hover mb-0">
                <thead>
                    <tr class="text-dark">
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Author Name</th>
                        <th scope="col">Author's primary affiliation</th>
                        <th scope="col">Surname</th>
                        <th scope="col">Email</th>
                        <th scope="col">Author Email</th>
                        <th scope="col">Country</th>
                        <th scope="col">Article Title</th>
                        <th scope="col">Keywords</th>
                        <th scope="col">Abstracted</th>

                    </tr>
                </thead>
                {% for s in my_sub %}
                <tbody>
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{s.firstname}}</td>
                        <td>{{s.author_name}}</td>
                        <td>{{s.affiliation_name}}</td>
                        <td>{{s.lastname}}</td>
                        <td>{{s.email}}</td>
                        <td>{{s.author_email}}</td>
                        <td>{{s.country}}</td>
                        <td>{{s.articletitle}}</td>
                        <td>{{s.keywords}}</td>
                        <td>{{s.abstracted}}</td>

                    </tr>
                </tbody>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
<!-- Recent Sales End -->


<!-- Content End -->
{% endblock body %}

templates/dashboard/update_posts.html
{% extends 'dashboard/dsh_base.html' %}
{% load static %}

{% load crispy_forms_tags %}


{% block title %}
  Update Post
{% endblock title %}


{% block body %}

<br>
<center>
    <h5 style="color: #009CFF;">Update Post</h5>
</center>


<form  style="margin: 10px; width:500px;" method=POST>
    {% csrf_token %}
    {{form.media}}
    {{form|crispy}}
    <br><br>

    <button style="color: white;" class="btn btn-info" type="submit">Update</button>
</form>




{% endblock body %}

templates/dashboard/users.html
{% extends 'dashboard/dsh_base.html' %}
{% load static %}


{% block title %}
  Users
{% endblock title %}

{% block body %}



<!-- Recent Sales Start --> 
<div class="container-fluid pt-4 px-4">
    <div class="bg-light text-center rounded p-4">
        <div class="d-flex align-items-center justify-content-between mb-4">
            <h6 class="mb-0">Users</h6>
            <a class="btn btn-sm btn-primary" href="{% url 'dashboard:adduser' %}"><i class="fa-solid fa-plus"></i></a>
        </div>

        <div class="table-responsive">
            <table class="table text-start align-middle table-bordered table-hover mb-0">
                <thead>
                    <tr id class="text-dark">
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Surname</th>
                        <th scope="col">Username</th>
                        <th scope="col">Email</th>
                    </tr>
                </thead>
                {% for u in my_user %}
                <tbody>
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{u.first_name}}</td>
                        <td>{{u.last_name}}</td>
                        <td>{{u.username}}</td>
                        <td>{{u.email}}</td>
                        <td><center><a class="btn btn-sm btn-primary" href="{% url 'dashboard:updateuser' u.id %}"><i class="fa-solid fa-gear"></i></a></center></td>
                        <td><center><a class="btn btn-sm btn-primary" href="{% url 'dashboard:deleteuser' u.id %}"><i class="fa-solid fa-trash"></i></a></center></td>
                    </tr>
                </tbody>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
<!-- Recent Sales End -->


{% endblock body %}